environment:
    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

    # Images for macOS
    IMAGE_MACOS_BIG_SUR:  big-sur-base
    IMAGE_MACOS_CATALINA: catalina-base

    # Branch to use for building the Zeek plugin.
    ZEEK_SPICY_BRANCH: main

pre_commit_task:
  container:
    dockerfile: ci/Dockerfile

  check_script:
    - pre-commit run -a --show-diff-on-failure

  pre_commit_cache:
    folder: /root/.cache/pre-commit

zkg_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS: 1
        - ZEEK_VERSION: 3.0.13-0
      - docker_arguments:
        - ZEEK_LTS: 1
        - ZEEK_VERSION: 4.0.3-0
      - docker_arguments:
        - ZEEK_LTS:
        - ZEEK_VERSION: 4.1.0-0
    cpu: 4
    memory: 12G

  install_spicy_script:
    - curl -o spicy-dev.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy-dev.deb
    - dpkg --install spicy-dev.deb
    - rm spicy-dev.deb

  prepare_script:
    - git clone --branch=$ZEEK_SPICY_BRANCH --recurse-submodules https://github.com/zeek/spicy-plugin
    - zkg install --skiptests --force spicy-plugin
    - rm -rf spicy-plugin
    - zeek -N _Zeek::Spicy

  test_script:
    - zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - zkg install --force --skiptests .

  check_script:
    - zeek -NN _Zeek::Spicy | grep -q ANALYZER_SPICY_TFTP
    - zeek -NN _Zeek::Spicy | grep Analyzer
    - (cd /tmp && zeek -r ${CIRRUS_WORKING_DIR}/tests/Traces/tftp_rrq.pcap local && test -e tftp.log && grep rfc1350.txt tftp.log)

  always:
      stderr_script: ./ci/show-zkg-stderr

zkg_macos_task:
  timeout_in: 120m

  osx_instance:
    image: $IMAGE_MACOS_BIG_SUR

  env:
    PATH: /opt/spicy/bin:${PATH}

  install_zeek_script:
    - brew install zeek

  install_spicy_script:
    - brew tap zeek/zeek
    - brew install spicy --HEAD

  prepare_script:
    - pip3 install 'zkg>=2.12.0' btest
    - zkg autoconfig && echo "@load packages" >>"$(zeek-config --site_dir)"/local.zeek
    - git clone --branch=$ZEEK_SPICY_BRANCH --recurse-submodules https://github.com/zeek/spicy-plugin
    - zkg install --skiptests --force spicy-plugin
    - rm -rf spicy-plugin
    - zeek -N _Zeek::Spicy

  test_script:
    - eval $(zkg env) && export PATH=$(zkg config bin_dir):$PATH && zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - eval $(zkg env) && export PATH=$(zkg config bin_dir):$PATH && zkg install --force --skiptests .

  check_script:
    - eval $(zkg env) && export PATH=$(zkg config bin_dir):$PATH && zeek -NN _Zeek::Spicy | grep -q ANALYZER_SPICY_TFTP
    - eval $(zkg env) && export PATH=$(zkg config bin_dir):$PATH && zeek -NN _Zeek::Spicy | grep Analyzer
    - eval $(zkg env) && export PATH=$(zkg config bin_dir):$PATH && cd /tmp && zeek -r ${CIRRUS_WORKING_DIR}/tests/Traces/tftp_rrq.pcap local && test -e tftp.log && grep rfc1350.txt tftp.log

  always:
      stderr_script: ./ci/show-zkg-stderr

standalone_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS:
        - ZEEK_VERSION: 4.0.3-0
    cpu: 4
    memory: 12G

  install_spicy_script:
    - curl -o spicy-dev.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy-dev.deb
    - dpkg --install spicy-dev.deb
    - rm spicy-dev.deb

  prepare_script:
    - git clone --branch=$ZEEK_SPICY_BRANCH --recurse-submodules https://github.com/zeek/spicy-plugin
    - (cd spicy-plugin && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/opt/spicy-plugin -G Ninja .. && ninja install)
    - rm -rf spicy-plugin
    - zeek -N _Zeek::Spicy

  install_script:
    - (mkdir build && cd build && PATH=/opt/spicy-plugin/bin:$PATH cmake -DCMAKE_INSTALL_PREFIX=/opt/spicy-analyzers -G Ninja .. && ninja -j 2 && ninja install)
    - rm -rf build

  test_install_script:
    - zeek -NN _Zeek::Spicy | grep Analyzer
    - PATH=/opt/spicy-plugin/bin:$PATH make -C tests test-install
    - (cd /tmp && zeek -r ${CIRRUS_WORKING_DIR}/tests/Traces/tftp_rrq.pcap spicy-analyzers && test -e tftp.log && grep rfc1350.txt tftp.log)
